### ISSUE TITLE
After Update to 1.2.1 -> PHP Error

### ISSUE THREAD

**Issue by righter1983** [stwa/google_addressbook#43]
Hi

I've updated to roundcube 1.2.1 and now I got this error in Settings -> Addressbook:
`
Fatal error: Uncaught Error: Class 'Google_Client' not found in /var/www/webmail.righter.ch/html/plugins/google_addressbook/google_func.php:24 Stack trace: #0 /var/www/webmail.righter.ch/html/plugins/google_addressbook/google_addressbook.php(131): google_func::get_client() #1 /var/www/webmail.righter.ch/html/program/lib/Roundcube/rcube_plugin_api.php(439): google_addressbook->preferences_list(Array) #2 /var/www/webmail.righter.ch/html/program/steps/settings/func.inc(1262): rcube_plugin_api->exec_hook('preferences_lis...', Array) #3 /var/www/webmail.righter.ch/html/program/steps/settings/edit_prefs.inc(28): rcmail_user_prefs('addressbook') #4 /var/www/webmail.righter.ch/html/index.php(291): include_once('/var/www/webmai...') #5 {main} thrown in /var/www/webmail.righter.ch/html/plugins/google_addressbook/google_func.php on line 24`

If I reverse back to 1.2.0 It's working again.

**Comment by stwa** [comment]
Do you use composer for plugin installation? How do you upgrade? If you extract the new version to a new folder and do not use composer, is the google-client-api also in the right place?

**Comment by righter1983** [comment]
Hi

No I've installed the plugins manually and upgraded roundcube via the recommended Shell Script.
I've now reinstalled the plugins via composer and now it's workin again.

Thanks for your help
