### ISSUE TITLE
documentation issue: what is source and what is target?

### ISSUE THREAD

**Issue by infra-hdc** [stwa/google_addressbook#44]
"This plugin lets you sync your Google Addressbook in readonly mode with Roundcube."
This is ambiguous phrase, at least for non-English users. Better description is with additon "(source is Roudcube, target is Google Address Book)". Or "Syncs contacts from Roundcube to Google Address Book". It would be nice to write exactly what the script does. My question is what is direction of synchronization?

**Comment by stwa** [comment]
Yes, you're right. The direction is from Google to Roundcube. I prefer something like "Syncs contacts from Google Addressbook to Roundcube" as description (no addition, just a sentence). Feel free to submit a pull request if you like to contribute, else I will update the documentation soon.
