### ISSUE TITLE
Roundcube Git Version and Authcode save

### ISSUE THREAD

**Issue by thoms3n** [stwa/google_addressbook#45]
To be able to save the Google AuthCode with the actual roundcube version from git, you need to replace the INPUT_POST function in google_addressbook.php

//$new_code = rcube_utils::get_input_value('rc_google_authcode', RCUBE_INPUT_POST);
   $new_code = rcube_utils::get_input_value('rc_google_authcode', rcube_utils::INPUT_POST);

**Comment by stwa** [comment]
Thanks for your contribution!
